# Generated by Django 4.1.3 on 2022-11-25 06:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('call_id', models.CharField(default='', max_length=50)),
                ('meta_data', models.TextField(blank=True, default='', help_text='string json format {}')),
                ('start_time', models.DateTimeField(null=True)),
                ('action_code', models.CharField(blank=True, default='', max_length=256)),
                ('ending_by', models.CharField(blank=True, default='', max_length=256)),
                ('status', models.CharField(choices=[('not_working', 'Not working'), ('working', 'Working'), ('done', 'Done')], default='not_working', max_length=15)),
                ('comment', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'call_qc',
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('call_campaign_id', models.CharField(default='', max_length=50)),
                ('name', models.CharField(max_length=128)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'campaign_qc',
            },
        ),
        migrations.CreateModel(
            name='Criteria',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_required', models.BooleanField(default=True)),
                ('is_monitor', models.BooleanField(default=True)),
                ('type', models.CharField(choices=[('BOOL', 'Boolean'), ('ENUM', 'Enumerate'), ('TEXT', 'Text')], max_length=25)),
                ('config', models.TextField(blank=True, help_text='separated by ;')),
                ('is_deleted', models.BooleanField(default=False)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='voicebot_qc.campaign')),
            ],
            options={
                'db_table': 'criteria_qc',
            },
        ),
        migrations.CreateModel(
            name='DataInput',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('customer_properties', 'Customer properties'), ('data_collection', 'Data collection'), ('system', 'System')], max_length=50)),
                ('field', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'data_input',
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('result', models.TextField(blank=True)),
                ('comment', models.TextField(blank=True)),
                ('call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='voicebot_qc.call')),
                ('criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='voicebot_qc.criteria')),
            ],
            options={
                'db_table': 'record',
            },
        ),
        migrations.AddField(
            model_name='criteria',
            name='data_input',
            field=models.ManyToManyField(blank=True, to='voicebot_qc.datainput'),
        ),
        migrations.CreateModel(
            name='CallList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=255)),
                ('status', models.CharField(choices=[('open', 'Open'), ('close', 'Close')], default='open', max_length=15)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('assign_to', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_call_lists', to=settings.AUTH_USER_MODEL)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_lists', to='voicebot_qc.campaign')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_call_lists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'call_list_qc',
            },
        ),
        migrations.AddField(
            model_name='call',
            name='call_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls', to='voicebot_qc.calllist'),
        ),
        migrations.CreateModel(
            name='UserCampaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('permission', models.CharField(choices=[('qc_member', 'QC member'), ('qc_lead', 'QC lead')], max_length=15)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_campaigns', to='voicebot_qc.campaign')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_user_campaigns', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_user_campaigns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_campaign',
                'unique_together': {('campaign', 'user')},
            },
        ),
    ]
