# Generated by Django 4.1.3 on 2022-11-28 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voicebot_qc', '0002_alter_calllist_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='calllist',
            name='condition_config',
            field=models.TextField(blank=True, help_text='list json string format'),
        ),
        migrations.AlterField(
            model_name='criteria',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criterias', to='voicebot_qc.campaign'),
        ),
        migrations.AlterField(
            model_name='criteria',
            name='data_input',
            field=models.ManyToManyField(blank=True, related_name='data_input_criterias', to='voicebot_qc.datainput'),
        ),
    ]
