# Generated by Django 4.1.3 on 2022-12-13 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voicebot_qc', '0004_alter_criteria_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datainput',
            name='campaign',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='data_input', to='voicebot_qc.campaign'),
        ),
        migrations.AlterUniqueTogether(
            name='call',
            unique_together={('call_list', 'call_id')},
        ),
    ]
