# Generated by Django 4.1.3 on 2022-12-14 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voicebot_qc', '0006_alter_datainput_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='record_path',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
